name: "pre-release"

on:
  push:
    branches: ["develop"] # TODO: change this to master when ready
    paths: ['*', 'installer/**', '.github/**']

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
       - name: Publish GitHub Release
         uses: "crowbarmaster/GH-Automatic-Releases@v1.6.0"
         with:
           repo_token: "${{ secrets.GITHUB_TOKEN }}"
           automatic_release_tag: "testing"
           prerelease: true
           title: "Development Build"
           generate_notes: false
           body: "Don't use this unless you're willing to report bugs!"
